openapi: "3.0.0"
info:
  title: "Tshirt Store REST API"
  description: "A Project of Tshirt Store, Creating a REST API for Tshirt Store"
  version: "1.0.1"
  contact:
    name: "Tshirt Store"
    url: "https://www.Tshirt.com"
    email: aliimranadil2@gmail.com

# servers:
#   - url: "https://localhost:5000/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:5000/api/v1"
#     description: for local host - regular

servers:
  - url: "{protocol}://localhost:5000/api/{version}"
    description: for local host - secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /signup:
    post:
      tags:
        - Authentication
      summary: returns an object with credetials of a new user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - photo
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                photo:
                  in: formData
                  description: The uploaded file data
                  type: file
                  required: true

      responses:
        200:
          description: All good and success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      _id:
                        type: integer
                  photo:
                    type: object
                    properties:
                      id:
                        type: string
                      secure_url:
                        type: string

        400:
          description: Bad Request
        500:
          description: Internal Server Error
